name: Build and deploy

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: npm install, test and lint
        run: |
          npm ci
          npm run build
  # deploy:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Use Node.js
  #     uses: actions/setup-node@v2
  #     with:
  #       node-version: 14.x
  #   - name: npm install, test and lint
  #     run: |
  #       npm ci
  #       npm run lint
  #       npm run test
